import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('launcher Windows sincronizza dipendenze',()=>{const text=fs.readFileSync('RUN-WINDOWS.bat','utf8');assert.match(text,/npm install --no-audit --no-fund/i);});
test('Vite preserva isolamento Tauri',()=>{const text=fs.readFileSync('vite.config.js','utf8');assert.match(text,/const host = process\.env\.TAURI_DEV_HOST/);assert.match(text,/src-tauri/);});
test('backend immagini resta locale',()=>{const text=fs.readFileSync('src-tauri/src/lib.rs','utf8');assert.doesNotMatch(text,/reqwest|https:\/\//i);});
test('interfaccia usa il design della suite',()=>{const main=fs.readFileSync('src/main.js','utf8');assert.match(main,/Comprami Un Caffè/);assert.match(main,/davstudios\.it/);const style=fs.readFileSync('src/styles.css','utf8');assert.match(style,/--accent:#006edb/);});
test('workflow GitHub pubblica release stabile con description bilingue',()=>{const text=fs.readFileSync('.github/workflows/release.yml','utf8');assert.match(text,/Verify release versions/);assert.match(text,/Read release description from tagged commit/);assert.match(text,/git log -1 --pretty=%b/);assert.match(text,/releaseBody:\s*\$\{\{ steps\.release_description\.outputs\.body \}\}/);assert.match(text,/prerelease:\s*false/);assert.doesNotMatch(text,/Stable release of _davIMAGE|generateReleaseNotes:\s*true/);});
test('set icone Tauri completo',()=>{for(const file of ['32x32.png','128x128.png','128x128@2x.png','app-icon.png','icon.ico','icon.icns'])assert.equal(fs.existsSync(`src-tauri/icons/${file}`),true,`${file} mancante`);});
test('metadata pacchetto _davstudios presenti',()=>{const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));const tauri=JSON.parse(fs.readFileSync('src-tauri/tauri.conf.json','utf8'));const cargo=fs.readFileSync('src-tauri/Cargo.toml','utf8');assert.equal(pkg.author,'_davstudios');assert.equal(pkg.license,'MIT');assert.equal(pkg.homepage,'https://davstudios.it');assert.equal(tauri.identifier,'studio.dav.image');assert.equal(tauri.bundle.publisher,'_davstudios');assert.equal(tauri.bundle.homepage,'https://davstudios.it');assert.equal(tauri.bundle.license,'MIT');assert.equal(tauri.bundle.licenseFile,'../LICENSE');assert.equal(tauri.bundle.linux.deb.section,'graphics');assert.equal(tauri.bundle.linux.deb.priority,'optional');assert.match(cargo,/license = "MIT"/);assert.match(cargo,/homepage = "https:\/\/davstudios\.it"/);});
